version: 2

models:

    - name: stg_customers
      description: Staged customer data from our jaffle shop app.
      columns: 
        - name: customer_id
          description: The primary key for customers.
          tests:
            - unique
            - not_null
        - name: first_name
          description: this is the first name of the customers.
        - name: last_name
          description: this is the last name of the customers.

    - name: stg_orders
      description: Staged order data from our jaffle shop app.
      columns: 
        - name: order_id
          description: Primary key for orders.
          tests:
            - relationships:
                to: ref('stg_customers')
                field: customer_id
        - name: status
          description: '{{ doc("order_status") }}'
          tests:
            - accepted_values:
                values:
                  - completed
                  - shipped
                  - returned
                  - placed
                  - return_pending
        - name: order_date
          description: This the date of the order.
       
    - name: stg_payments
      description: Staged payments data from our jaffle shop app.
      columns: 
        - name: payment_id   
          description: Primary key for payments. 
        - name: payment_method
          description: '{{ doc("payment_method") }}' 

          
          
          
        